import { NestFactory } from '@nestjs/core';
import { AppModule } from '../app.module';
import { DataSource, Like } from 'typeorm';
import { PaymentRequest } from '../modules/shared/entities/payment-request.entity';
import { User } from '../modules/shared/entities/user.entity';
import { Logger } from '@nestjs/common';

async function bootstrap() {
  const logger = new Logger('SeederClear');
  logger.log('Starting DB Cleanup for Seeded Data...');

  const app = await NestFactory.createApplicationContext(AppModule);
  const dataSource = app.get(DataSource);

  const userRepo = dataSource.getRepository(User);
  const prRepo = dataSource.getRepository(PaymentRequest);

  // Find all seeded Payment Requests first
  const seededRequests = await prRepo.find({
    select: ['id'],
    where: { requestNumber: Like('SEED-PRF-%') },
  });

  const requestIds = seededRequests.map((pr) => pr.id);

  if (requestIds.length > 0) {
    logger.log(
      `Found ${requestIds.length} seeded Payment Requests. Cleaning up related records...`,
    );

    // Disable immutability trigger temporarily
    await dataSource.query(
      'ALTER TABLE approval_logs DISABLE TRIGGER trg_approval_logs_immutable',
    );

    // Delete related entities to prevent foreign key violations
    await dataSource.query(
      'DELETE FROM approval_logs WHERE payment_request_id = ANY($1)',
      [requestIds],
    );

    // Re-enable trigger
    await dataSource.query(
      'ALTER TABLE approval_logs ENABLE TRIGGER trg_approval_logs_immutable',
    );

    await dataSource.query(
      'DELETE FROM payment_breakdown_items WHERE payment_request_id = ANY($1)',
      [requestIds],
    );
    await dataSource.query(
      'DELETE FROM receipt_files WHERE payment_request_id = ANY($1)',
      [requestIds],
    );

    // 1. Delete all Payment Requests generated by seeder
    const prResult = await prRepo.delete({
      requestNumber: Like('SEED-PRF-%'),
    });
    logger.log(`🧹 Deleted ${prResult.affected || 0} seeded Payment Requests.`);
  } else {
    logger.log(`🧹 No seeded Payment Requests found.`);
  }

  // 2. Delete all Users generated by seeder (Prefix: seed_)
  const userResult = await userRepo.delete({
    email: Like('seed_%@example.com'),
  });
  logger.log(`🧹 Deleted ${userResult.affected || 0} seeded Users.`);

  logger.log(
    '✅ Seed cleanup completed successfully. Your original data is safe!',
  );

  await app.close();
}

bootstrap().catch((err) => {
  console.error('Unhandled error during seed cleanup:', err);
});
